# Generated by Django 2.2.10 on 2020-03-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='delay',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='tag',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
